version: "3.8"

services:
  springboot-app:
    build: .
    image: wlwl45wl/wookportfolio:latest
    container_name: springboot-app
    ports:
      - "8089:8089"
    restart: always

  nginx:
    build: ./nginx
    container_name: wook-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
      - /etc/letsencrypt/live/wookportfolio.duckdns.org/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/wookportfolio.duckdns.org/privkey.pem:/etc/nginx/certs/privkey.pem:ro
    depends_on:
      - springboot-app
    restart: always