version: "3.8"

services:
  springboot-app:
    build: .
    image: wlwl45wl/wookportfolio:latest
    container_name: springboot-app
    ports:
      - "8089:8089"
    restart: always

  nginx:
    build: ./nginx
    container_name: wook-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
      - /home/ubuntu/certs:/etc/nginx/certs:ro
    depends_on:
      - springboot-app
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
      - /home/ubuntu/certs:/etc/nginx/certs:ro
    depends_on:
      - springboot-app
    restart: always