version: "3.8"

services:
  springboot-app:
    image: wlwl45wl/wookportfolio:latest   # ← Docker Hub 이미지 (Actions가 최신 이미지를 push)
    container_name: springboot-app
    ports:
      - "8089:8089"
    restart: always

  nginx:
    image: wook-nginx:latest
    container_name: wook-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/lib/letsencrypt
    depends_on:
      - springboot-app
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/lib/letsencrypt
    entrypoint: >
      /bin/sh -c 'trap exit TERM;
      while :;
      do certbot renew --webroot -w /var/lib/letsencrypt --deploy-hook "nginx -s reload";
      sleep 12h & wait $${!};
      done;'
    restart: always