version: "3.8"

services:
  springboot-app:
    build: .
    image: wlwl45wl/wookportfolio:latest
    container_name: springboot-app
    expose:
      - "8089"
    restart: always

  nginx:
    build: ./nginx/conf.d        # ← 여기서 로컬 Dockerfile로 이미지 빌드
    container_name: wook-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/lib/letsencrypt
    depends_on:
      - springboot-app
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/lib/letsencrypt
    entrypoint: >
      /bin/sh -c 'trap exit TERM;
      while :;
      do certbot renew --webroot -w /var/lib/letsencrypt --deploy-hook "docker exec wook-nginx nginx -s reload";
      sleep 12h & wait $${!};
      done;'
    restart: always